version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - unconvert
    - unparam

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam

issues:
  exclude-dirs:
    - testdata
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
