version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - unconvert
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
    paths:
      - testdata

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
